version: '3.8'

services:
  frontend:
    build: ./client/apifrontend
    container_name: react-frontend
    ports:
      - "3000:3000"

  backend:
    build: ./server
    container_name: express-backend
    ports:
      - "28017:28017"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
